### ISSUE TITLE
dependencies.rosinstall

### ISSUE THREAD

**Issue by WHGang** [ros-industrial-consortium/tesseract#111]
How to run dependencies.rosinstall? thanks

**Comment by mpowelson** [comment]
Similarly to with [TrajOpt #124](https://github.com/ros-industrial-consortium/trajopt_ros/issues/124), this is mostly just here for CI. You will need to make sure that you clone Tesseract with submodules though. See [HERE](https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules)

**Comment by mpowelson** [comment]
I'm going to close this. If you are still needing more information, feel free to reopen it.
