### ISSUE TITLE
CTest Verbosity

### ISSUE THREAD

**Issue by marip8** [ros-industrial-consortium/tesseract#139]
Was #136 supposed to print the results of CTest to the terminal? If so, it hasn't worked for me on my local machine (Ubuntu 16.04, ROS Kinetic) and it doesn't seem to have worked on the Kinetic CI machine either (see [latest build of #126](https://travis-ci.com/ros-industrial-consortium/tesseract/jobs/241734808#L3538) which has been rebased onto master)

**Comment by Levi-Armstrong** [comment]
It looks like ci suppress the output so even if this is set the only way to see it is turn on verbose for ci but I also run into issues where ci is stopped because the log get to long.
