### ISSUE TITLE
stray NodeHandle instance in kdl_env.cpp

### ISSUE THREAD

**Issue by arocchi** [ros-industrial-consortium/tesseract#14]
In the implementation of [KDLEnv, at line 67](https://github.com/ros-industrial-consortium/tesseract/blob/3ce8c8ba252318ee02155401ef1d3d17eed12bc4/tesseract_ros/src/kdl/kdl_env.cpp#L67), there is a stray `NodeHandle` instance. 

Is there a specific reason you are forcing `KDLEnv` to be used with a `roscore`? It looks like the class could be useful (and used) even without a `roscore` running.

**Comment by Levi-Armstrong** [comment]
This is an error.

**Comment by Levi-Armstrong** [comment]
@arocchi Is it ok to close this issue?

**Comment by arocchi** [comment]
@Levi-Armstrong thank you!
