### ISSUE TITLE
How to add multiple "robots" to the same Environment?

### ISSUE THREAD

**Issue by haudren** [ros-industrial-consortium/tesseract#142]
I've been experimenting a bit more with Tesseract / TrajOpt and it seems to give good results :+1: 

However I would like to do the following:
- Create an Environment containing my robot via `Tesseract::init(urdf, srdf, locator)`
- Add collision shapes and other objects independently

So far I've been constructing them by hand (create Link, create Joint, then call `addLink`), but I would ideally load them from a URDF file. However a quick look at the documentation tells me that:
- `parseURDF` either returns a `scene_graph` or appends to a `scene_graph`
- `Environment` only has a `const` getter for its scene graph

I believe that I could get away with any of the following:
1. Merging my URDFs using xacro
2. Create a `scene_graph`, parse the various URDFs into it, and finally use `Tesseract::init`
3. By hand traverse each loaded model and add their Link / Joints to the scene
4. Each time a collision shape is to be added, update a stored `scene_graph` and call again `Environment::init`

Options 1. and 2. are suboptimal because they don't allow for online modification of the environment but 3. means writing quite a lot of code and 4. feels like a big hack.

Ideally I would like to reach something akin to `Environment::addRobot(parseURDF(urdf))` that would allow me to add "robots" (they are static for now) to the environment.

**Comment by Levi-Armstrong** [comment]
Boost graph supports the notion of subgraphs. I had planned to implement this to support your use case but have not gotten around to it. For now it would not be to much work to add a method to the environment as you suggested to that takes a SceneGraph as shown below.

```
  virtual bool addSceneGraph(const tesseract_scene_graph::SceneGraph& scene_graph);

  virtual bool addSceneGraph(const tesseract_scene_graph::SceneGraph& scene_graph, tesseract_scene_graph::Joint joint);
```

**Comment by Levi-Armstrong** [comment]
Link to the boost subgraph https://www.boost.org/doc/libs/1_55_0/libs/graph/doc/subgraph.html

**Comment by johnwason** [comment]
We have been able to represent multiple robots by having multiple "groups" in the SRDF file. Right now it isn't clear how you specify to concurrently plan multiple robots since the planning requests all have a "std::string manipulator" parameter. Is there a way to send a trajopt request to concurrently plan for multiple robots?

**Comment by Levi-Armstrong** [comment]
Currently you create a single joint group that includes all of the joints you would like to plan for.

**Comment by johnwason** [comment]
@Levi-Armstrong I tried planning with trajopt using multiple robots, but it wasn't smart enough to plan for when the arms needed to avoid each other while passing through the same space.. I will probably need to use the OMPL/TrajOpt hybrid, but it doens't have multi-robot support.

Also, the SRDFModel class is immutable, and doesn't work with SWIG because of nested classes.

**Comment by Levi-Armstrong** [comment]
> I tried planning with trajopt using multiple robots, but it wasn't smart enough to plan for when the arms needed to avoid each other while passing through the same space.

Did you have continuous collision checking enabled? I would expect it not to work if using discrete collision checking.

> I will probably need to use the OMPL/TrajOpt hybrid, but it doens't have multi-robot support.

I should; what issue did you have? Multiple robot should be defined as a single joint kinematics group.

@johnwason  Do you have a test case I
