### ISSUE TITLE
Switch to GTest imported targets?

### ISSUE THREAD

**Issue by haudren** [ros-industrial-consortium/tesseract#144]
Currently, the code uses `GTEST_BOTH_LIBRARIES`. From a cursory look, I believe we should instead switch to using `GTest::GTest` and `GTest::GTestMain`, because `GTest` has a transient dependency on `Thread`

https://cmake.org/cmake/help/v3.15/module/FindGTest.html

I also noticed that the test code in some other repos (`opw_kinematics` and `descartes_ikfast` at least) seems to contain typos, where the imported target is called `gtest::GTest`, which triggers the inclusion of the external project instead of using the system version.

**Comment by Levi-Armstrong** [comment]
> Currently, the code uses GTEST_BOTH_LIBRARIES. From a cursory look, I believe we should instead switch to using GTest::GTest and GTest::GTestMain, because GTest has a transient dependency on Thread

I agree.


> I also noticed that the test code in some other repos (opw_kinematics and descartes_ikfast at least) seems to contain typos, where the imported target is called gtest::GTest, which triggers the inclusion of the external project instead of using the system version.

I will look into those repositories.

**Comment by Levi-Armstrong** [comment]
This has been addressed in PR #149 and PR's have been opened against opw_kinematics and descartes_light.

**Comment by haudren** [comment]
Thank you!
