### ISSUE TITLE
Add clang to package.xml

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract#198]
I am getting cases where clang-tidy will fail when it shouldn't. Specifically I get unused parameter errors when they are actually used.

**Comment by mpowelson** [comment]
According to @Levi-Armstrong this is a known issue with Clang-tidy. The debian for clang-tidy is missing the dependency on clang. The solution is to install clang-tidy 6 as well as clang-6.0.

**Comment by gavanderhoorn** [comment]
Should (could) we explicitly add the dependency on whatever doesn't get installed?

If it ever gets fixed upstream, the additional dependency is already resolved. So it would not 'hurt'.

**Comment by mpowelson** [comment]
I would think we probably could. I guess we would just add that to tesseract_macros.cmake? I suppose we could do a check for it the same way we do clang-tidy and look for versions that we know work.

**Comment by gavanderhoorn** [comment]
I was thinking more of adding the separate dependencies (ie: clang and clang-tidy) to the package manifest of *some* package. That would allow `rosdep` to install them, if they're not present on the system already.

Are we right now depending on `clang-tidy` to pull in clang? If so, perhaps adding clang itself as a dependency would avoid the problem you report.

**Comment by Levi-Armstrong** [comment]
These dependencies should probably be added to tesseract_common as build dependencies as @gavanderhoorn suggested.

**Comment by Levi-Armstrong** [comment]
Addressed by #231
