### ISSUE TITLE
Add support for SRDF model in tesseract_python

### ISSUE THREAD

**Issue by haudren** [ros-industrial-consortium/tesseract#206]
I was playing around with `tesseract_python`, and noticed that one feature is missing (and apparently the code is commented in `tesseract.i` ): support for SRDF model.

I use this area of the code mostly to have access to the group states, that are quite useful when setting up planning problems in a ROS environment (typically set the initial configuration to a known pose).

I will try to get a corresponding PR in in the coming days, but this issue can serve for discussion before that.

**Comment by Levi-Armstrong** [comment]
Yea, I believe @johnwason said there is issue with the library that was causing an issue with swig. I think it was because it had nested structs within the class. Feel free to restructure the srdf library.

**Comment by Levi-Armstrong** [comment]
@haudren Has this been addressed?

**Comment by haudren** [comment]
Yes, this was fixed by #208 .
