### ISSUE TITLE
CMake Error finding opw_kinematics 

### ISSUE THREAD

**Issue by bgd29** [ros-industrial-consortium/tesseract#246]
Trying to build tesseract using catkin build, but I get errors because my workspace doesn't have tesseract dependencies (opw_kinematics, descartes_light etc) e.g. "Could not find a package configuration file provided by "opw_kinematics". If I manually add the dependecies I am able to build but the tesseract_ros_examples crash "error while loading shared libraries: libtrajopt_utils.so" .
I did clone the repo using --recursive, so I'm not sure what the correct workflow is or if there is something (obvious) I'm missing.

**Comment by Levi-Armstrong** [comment]
You should be able to run the rosinstall file in the main directory which should pull in all of these dependencies.

**Comment by Levi-Armstrong** [comment]
Did running the rosinstall resolve the issue?

**Comment by bgd29** [comment]
Yes, rosinstall solved the problem I had above with the missing packages. I noticed tesseract_ros was removed from the repo, is that being reworked?

**Comment by mpowelson** [comment]
It has been moved to https://github.com/ros-industrial-consortium/tesseract_ros and https://github.com/ros-industrial-consortium/tesseract_ros2 in order to better support ROS1/ROS2 compatibility

**Comment by bgd29** [comment]
I'm still having the crash (seg fault) problem with any of the examples from /tesseract_ros_examples. Should I close this issue and open a new one over at https://github.com/ros-industrial-consortium/tesseract_ros ?

**Comment by Levi-Armstrong** [comment]
Yea that would be better.
