### ISSUE TITLE
"Failed to calculate jacobian" when using KDLJointKin

### ISSUE THREAD

**Issue by arocchi** [ros-industrial-consortium/tesseract#27]
it looks to me like `KDLJointKin` does not implement successfully `addAttachedLink` (`parent_link_name` is never stored) and thus also `calcJacobian` (if we request the Jacobian of an attached link it will fail instead of computing the Jacobian of its parent link and then transforming it into the attached link).

The problem became apparent when using TrajOpt with a manipulator with an attached object.

**Comment by Levi-Armstrong** [comment]
It looks like I did not update this to handle attached links like what is done in the chain library. This should not be to hard to update.

**Comment by Levi-Armstrong** [comment]
I should have PR posted today with a fix I am currently writing some unit tests.

**Comment by Levi-Armstrong** [comment]
@arocchi I believe this issue has been resolved with PR #32 can you confirm?

**Comment by arocchi** [comment]
confirmed, thanks Levi.
