### ISSUE TITLE
Tesseract Collision assert triggering

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract#276]
I am getting an assert triggered [HERE](https://github.com/ros-industrial-consortium/tesseract/blob/02cd020bd73ebcb9fd356494d3874f07aedc1fa7/tesseract/tesseract_collision/include/tesseract_collision/core/common.h#L128) during a box-box check using the BulletDiscreteSimpleManager. Are the if statements set up correctly here?

**Comment by Levi-Armstrong** [comment]
Yea, have you rebased on the latest? I ran into this when updating the unit tests for tesseract_collision in PR #274 and I believe I fixed it.

**Comment by mpowelson** [comment]
I still seem to be getting it. Is there a reason why if(found) the contact test type should not be first?

**Comment by Levi-Armstrong** [comment]
Which contact manager is causing the assert?

**Comment by mpowelson** [comment]
BulletDiscreteSimpleManager. It happens when I run the benchmarks in debug.

**Comment by Levi-Armstrong** [comment]
Does the benchmark run multiple threads?

**Comment by mpowelson** [comment]
I'm not sure. I think it can.

**Comment by mpowelson** [comment]
This was my own fault. I was not clearing the contact results before calling contactTest. Apparently this is not necessarily a problem (you may not notice in release), but will result in poor performance.

I had to change
```
  ContactResultMap result;
  for (auto _ : state)
  {
    info.contact_manager_->contactTest(result, info.contact_test_type_);
  }
```
to
```
  ContactResultMap result;
  for (auto _ : state)
  {
    result.clear();
    info.contact_manager_->contactTest(result, info.contact_test_type_);
  }
```
