### ISSUE TITLE
Add colcon.pkg file to every package.

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial-consortium/tesseract#302]
In order for pure cmake packages to be discovered by the ROS2 ecosystem it requires an environment hook so the package gets added to the environment variable AMENT_PREFIX_PATH.

The following must be done.

Add this to the tesseract_package cmake macro.
```
file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/share/ament_index/resource_index/packages/${PROJECT_NAME} "")
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/share/ament_index/resource_index/packages/${PROJECT_NAME} DESTINATION share/ament_index/resource_index/packages)

file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/share/${PROJECT_NAME}/hook/ament_prefix_path.dsv "prepend-non-duplicate;AMENT_PREFIX_PATH;")
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/share/${PROJECT_NAME}/hook/ament_prefix_path.dsv DESTINATION share/${PROJECT_NAME}/hook)
```

Create a colcon.pkg file in every package with the following content.
```
{
    "hooks": ["share/<package_name>/hook/ament_prefix_path.dsv"]
}
```

For more details see this [issue](https://github.com/ros-infrastructure/rosdep/issues/724#issuecomment-642346756)

@schornakj

**Comment by mpowelson** [comment]
Addressed in #303
