### ISSUE TITLE
Continuous Joints don't show up in active joint list

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract#344]
Getting active joints like `tesseract->getEnvironment()->getActiveJointNames())` does not show the continuous joints

**Comment by Levi-Armstrong** [comment]
@mpowelson Has this been addressed?

**Comment by mpowelson** [comment]
It was merged into master in 6dee0e

**Comment by Levi-Armstrong** [comment]
I will rebase feature/CommandLanguage
