### ISSUE TITLE
KDL State solver cloning is slow

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial-consortium/tesseract#358]
It has been identified with the recent ability to clone the environment that the state solver clone in release takes about a second. Leveraging valgrind callgrind it was determined that 41% of the time is spent processing the graph to confirm it is a tree structure and another 47% of the time is spent building the tree. This currently happens because the onEnvironmentChanged method for the KDL state solver was a lazy implementation on my part. All of the time can be recovered by actual processing the environment command instead of rebuilding everything for every change in the environment. All of the code is in the createKDETree function to fully implement the onEnvironmentChange. Also will put the check for if it is a tree in an assert.

![image](https://user-images.githubusercontent.com/9803128/90964282-c9c26e00-e484-11ea-9912-1b1f79e46137.png)

- [x] Encapsulate the isTree check in an assert
- [ ] Process the command in the environment change callback instead of rebuilding the tree.
 

@mpowelson  Issue is creating.

**Comment by mpowelson** [comment]
@Levi-Armstrong What executable are you using to profile this? The tesseract_environment unit tests?

**Comment by Levi-Armstrong** [comment]
Yea the environment unit test.

**Comment by Levi-Armstrong** [comment]
Well it turns out that KDL tree does not allow you to modify segments after they have been added to the tree. It looks like you have to recreate the tree if you make any modifications. This seems odd but I will keep exploring. In mean time I have added a new state solver in PR #360 which should provided an alternative providing a better solution for Tesseract.

**Comment by Levi-Armstrong** [comment]
Closing because a new state solver has been implemented to overcome the challenges with the KDLStateSolver.

**Comment by mpowelson** [comment]
@Levi-Armstrong I thought this might be interesting to you now that the manipulator manager has been added.

![Screenshot from 2020-10-13 14-07-58](https://user-images.githubusercontent.com/12128406/95910693-ad90ce00-0d5d-11eb-8758-2c63bb232e64.png)
