### ISSUE TITLE
Modifying kinematic limits during execution

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract#380]
I want to do something like this.
```
if (mode == "SPECIAL_PLANNING_CASE")
  kin->setLimits(...);
```

I seems like it should be as simple as just adjusting the kinematic limits in the kdl data structure. Do you think there are other methods that will have to be called again? For instance, would Tesseract objects for example have to be reinitialized? I'm thinking the answer is no since I don't see anywhere where kinematics gets processed into another data structure, but I wanted to see if anyone else (@Levi-Armstrong) knew of anything.

**Comment by Levi-Armstrong** [comment]
It only needed at the TesseractKinematics object or are you also wanting to modify it in environment ?

**Comment by mpowelson** [comment]
I want to modify it everywhere needed for planning. So I suppose in the environment as well.

**Comment by Levi-Armstrong** [comment]
I would create a new command and apply it that way, should be to much work. Maybe ModifyJointLimitsCommand?

**Comment by mpowelson** [comment]
Ok. Depending on if I end up needing to do this, I may add that later this week. I'll assign this to myself if I start it.

**Comment by mpowelson** [comment]
@Levi-Armstrong I think I am going to take a stab at this.

**Comment by mpowelson** [comment]
See #415

**Comment by Levi-Armstrong** [comment]
Integrated in #415.
