### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract#408]
Using this thread to keep track of improvements found while profiling

- [x] Get rid of the environment clone in WaypointInCollision
- [x] Add clone cache as discussed [here](https://github.com/ros-industrial-consortium/tesseract_ros/issues/51) (See PR #440)
- [x] Get rid of duplicate environment clone in Tesseract->clone (PR #409)

**Comment by mpowelson** [comment]
Starting off with a callgrind calltree of a motion planning pipeline. For this particular run the processes were
- FixStateBounds - 1.6%
- FixStateCollision - 69.9%
- SimpleMotionPlanner - 2.89%
- DiscreteContactChecker - 19.10%
- IterativeSplineParameterization - 6.34%

Main takeaway: **We need to get rid of the environment clone in WaypointInCollision**

![pipeline](https://user-images.githubusercontent.com/12128406/95913475-86d49680-0d61-11eb-869b-dd4e0e0e834d.png)

**Comment by Levi-Armstrong** [comment]
@mpowelson I could not find where you posted the performance for the tesseract clone but it did not look correct the functions it was calling so I took a look. If you replace the clone method with what is below does it performa better?

```
Tesseract::Ptr Tesseract::clone() const
{
  auto clone = std::make_shared<Tesseract>();

  clone->environment_ = environment_->clone();
  clone->manipulator_manager_->clone(clone->environment_);
  clone->init_info_ = init_info_;
  clone->initialized_ = initialized_;
  clone->find_tcp_cb_ = find_tcp_cb_;

  return clone;
}
```

**Comment by mpowelson** [comment]
Sorry, I posted it in the other (closed) thread about cloning the environment. I'll post it here to keep it all in one place.

![Screenshot from 2020-10-13 14-07-58](https://user-images.githubusercontent.com/12128406/96001614-75d56500-0df5-11eb-8ea0-66e8f549e324.png)

**Comment by Levi-Armstrong** [comment]
Ah, thank you. I believe the change above should improve the performance of the clone.

**Comment by mpowelson** [comment]
Yeah that does look like it should be faster. Before we were cloning the environment twice.

**Comment by Levi-Armstrong** [comment]
It sure was.

**Comment by mpowelson** [comment]
I added a benchmark for cloning. It is not comprehensive, but cloning a Tesseract initialized with the lbr iiwa srdf. I change the clone to this 
```
Tesseract::Ptr Tesseract::clone() const
{
  auto clone = std::make_shared<Tesseract>();

  if(environment_)
  {
    clone->environment_ = environment_->clone();
    if(manipulator_manager_)
      clone->manipulator_manager_ = manipulator_manager_->clone(clone->environment_);
  }

  clone->init_info_ = init_info_;
  clone->initialized_ = initialized_;
  clone->find_tcp_cb_ = find_tcp_cb_;

  return clone;
}
```
Before:
```
--------------------------------------------------------------------
Benchmark                             Time           CPU Iterations
--------------------------------------------------------------------
BM_TESSERACT_CLONE/real_time       3560 us       3560 us        193
```

After:
```
--------------------------------------------------------------------
Benchmark                             Time           CPU Iterations
--------------------------------------------------------------------
BM_TESSERACT_CLONE/real_time        235 us        235 us       2778

```

**Comment by Levi-Armstrong** [comment]
That looks a lot better.

**Comment by mpowelson** [comment]
I was thinking about trying out https://github.com/yse/easy_profiler for getting real world timings of a motion planning pipeline. Any thoughts? Have you used anything else? This one looks simple enough to use. It claims it only slows it by 1-2%

**Comment by Levi-Armstrong** [comment]
Looks good to me. I did add the ability to turn on profiling for just the taskflow which outputs a json file in the temp directory to load in the profTaskflow tool. Thought this could be used through the code. Is it actively being maintained?

**Comment by mpowelson** [comment]
I forgot about the taskflow profiling. That might be useful to look at too.

**Comment by mpowelson** [comment]
Code frequency has definitely fallen off, but it was last released end of 2019. It may just be mature enough that it doesn't need much more development these days. That said, I just picked the top google hit for "lightweight C++ profiler github"

**Comment by mpowelson** [comment]
I think "Get rid of the environment clone in WaypointInCollision" may have been already done, but I did a bit of cleanup in #444.
