### ISSUE TITLE
LVS interpolation segfaults on (j2-j1).norm()

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract#422]
This specific case occurs in lvs_interpolation.cpp line 407. To replicate, run the tesseract_process_managers unit tests switching the simple planner to use the LVS profile in simple_motion_planner.cpp (line 75). After #412 is merged, change

```
plan_profiles["DEFAULT"] = std::make_shared<SimplePlannerDefaultPlanProfile>();
```
to
```
plan_profiles["DEFAULT"] = std::make_shared<SimplePlannerLVSDefaultPlanProfile>();
```

**Comment by Levi-Armstrong** [comment]
@mpowelson Has this been resolved with the latest changes to LVS?

**Comment by mpowelson** [comment]
I'm not sure. Like I said though, if you change the simple planner to use LVS instead, the tests should start failing. So if you are using it, then I'd guess you probably fixed it.

**Comment by Levi-Armstrong** [comment]
Yea it is the default now and everything is working. I will close, please reopen if you try it again and experience issues.
