### ISSUE TITLE
Won't build on Ubuntu Xenial 16.04 ROS Kinetic

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract#457]
Preemptively adding this issue to document it. Support for Kinetic was dropped in commit 70211e1ffd2e37fad4b4185eb8993440fb318558 when C++17 was added to the tesseract_macros.

**Comment by gavanderhoorn** [comment]
Pedantic, but: this is not about Xenial or Kinetic, but about the version of the compiler used.

**Comment by mpowelson** [comment]
Yeah. I suppose its important to note that it very well may still work. We just won't be supporting it. The CI build has been removed.
