### ISSUE TITLE
-Werror=sign-conversion errors

### ISSUE THREAD

**Issue by johnwason** [ros-industrial-consortium/tesseract#464]
I am getting a bunch of errors in unit tests due to sign conversion errors, for example:

```
tesseract/tesseract/tesseract_collision/include/tesseract_collision/test_suite/collision_box_cylinder_unit.hpp:148:55: error: conversion to ‘std::array<Eigen::Matrix<double, 3, 1>, 2>::size_type’ {aka ‘long unsigned int’} from ‘__gnu_cxx::__alloc_traits<std::allocator<int>, int>::value_type’ {aka ‘int’} may change the sign of the result [-Werror=sign-conversion]
  148 |     EXPECT_NEAR(result_vector[0].nearest_points[idx[0]][0], 0.5, 0.001);
      |                                     
```

I am seeing these errors on my feature/CommandLanguagePython branch, but not on the base feature/CommandLanguage branch. I am not sure why this is occurring. The link to the branch is here: https://github.com/johnwason/tesseract/tree/feature/CommandLanguagePython
tesseract_python isn't building yet, so add `CATKIN_IGNORE` to that directory for now. I am using Ubuntu 20.04 x64 with ROS Noetic.

**Comment by Levi-Armstrong** [comment]
For lines 148  try adding a static_cast<std::size_t>(idx[0]) and 149 static_cast<std::size_t>(idx[1]) to see if the error goes away here.

```
 EXPECT_NEAR(result_vector[0].nearest_points[idx[0]][0], 0.5, 0.001);
 EXPECT_NEAR(result_vector[0].nearest_points[idx[1]][0], -0.05, 0.001);
```

**Comment by Levi-Armstrong** [comment]
The issue was that c-arrays were switched to std::array triggering the `-Werror=sign-conversion`
