### ISSUE TITLE
Fix Profile XML parsing and writing

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract#501]
Xml parsing is broken on feature/CommandLanguage due to the API changes. I don't think I would let that stop us from merging it into master, but we might want to fix that at some point. Its also worth noting that the tests don't detect that it is broken, which indicates a flaw there as well.

Search for the TODOs in tesseract_motion_planners and it should come up.

**Comment by Levi-Armstrong** [comment]
Moved to tesseract_planning repository
