### ISSUE TITLE
addJoint() in Environment

### ISSUE THREAD

**Issue by johnwason** [ros-industrial-consortium/tesseract#504]
`addJoint()` is implemented in the scene graph, but not exposed to `Environment`. It looks like the idea is to have joints be added with links. This is a safer design, but prevents the creation of closed kinematic loops. Is this an intentional design choice?

**Comment by Levi-Armstrong** [comment]
Yea, it was intentional until a state solver was added that supports closed kinematic loops. This was the thought around adding direct support for subgraph where each subgraph would be equivalent to a model which could have its own state solver. Do you a current use case?

**Comment by johnwason** [comment]
I am working on the Robot Raconteur tesseract server and noticed it was missing. I don't think that most planners support closed loops, so I will probably leave off the function. I wanted to make sure.
