### ISSUE TITLE
Does tesseract_python require yaml-cpp and jsoncpp?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial-consortium/tesseract#507]
@johnwason Does tesseract_python required yaml-cpp and jsoncpp? It is listed in the tesseract_python_module.cmake but not listed in the package.xml so not sure if they should be added or if they should be removed from tesseract_python_module.cmake.

**Comment by johnwason** [comment]
jsoncpp is required. I think yaml-cpp is there to fix some build issues I have run in to. These are dependencies of the packages already included in package.xml so I don't think they need to be explicitly included. They should be implicitly included from the other dependencies.

**Comment by Levi-Armstrong** [comment]
Addressed by #508
