### ISSUE TITLE
checkJoints does not actually check for joint limits

### ISSUE THREAD

**Issue by haudren** [ros-industrial-consortium/tesseract#551]
While experimenting with OPW Kinematics, I realized that `checkJoints` does not check joint limits. Indeed, even when a joint is detected to be out of limits this `return true` is always hit:
https://github.com/ros-industrial-consortium/tesseract/blob/f33ba348093aa7cc73df6c17450dbad0eeda11c9/tesseract_kinematics/src/opw/opw_inv_kin.cpp#L119

I fixed it in my branch:
https://github.com/haudren/tesseract/commit/cb59289c92ac5f3f152f2ce78ea00cb5f9ed4326

But while adding the tests, I noticed it broke some other tests that are checking that a vector of `numeric_limits<double>::max` returns true when passed to `checkJoints`. So, is it:
- The header description that is wrong ( https://github.com/ros-industrial-consortium/tesseract/blob/f33ba348093aa7cc73df6c17450dbad0eeda11c9/tesseract_kinematics/include/tesseract_kinematics/core/inverse_kinematics.h#L100 )
- The tests that are incorrect

Thanks

**Comment by Levi-Armstrong** [comment]
I will go through and fix the `checkJoints` function.

**Comment by haudren** [comment]
@Levi-Armstrong : Any progress on this? I can take care of it if you would just let me know which alternative you prefer :)

**Comment by Levi-Armstrong** [comment]
Just created a [PR](https://github.com/ros-industrial-consortium/tesseract/pull/564)

**Comment by haudren** [comment]
The PR mentioned seems to fix it for OPW, but the newly merged UR kinematics ( #556 ) seems to re-introduce it :thinking:

**Comment by Levi-Armstrong** [comment]
Yep, the PR was not updated. PR #565 should fix the issues.

**Comment by Levi-Armstrong** [comment]
Please reopen if the issue has not been resolved.
