### ISSUE TITLE
Threading issues in environment

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract#559]
I made this unit test that fails. It adds and removes a link repeatedly in different threads.
https://github.com/mpowelson/tesseract/tree/bug/threaded_environment

**Comment by mpowelson** [comment]
@Levi-Armstrong Do you think you could take a look? Possibly related to https://github.com/ros-industrial-consortium/tesseract_ros/issues/90

**Comment by mpowelson** [comment]
[This](https://github.com/mpowelson/tesseract/blob/769c5ad5ee4ee985247bbbcf8d1805d3b1834c36/tesseract_environment/src/core/environment.cpp#L169) seems like a problem. Doesn't this lock immediately go out of scope?

**Comment by Levi-Armstrong** [comment]
Fixing it now.

**Comment by Levi-Armstrong** [comment]
The last commit in [this](https://github.com/ros-industrial-consortium/tesseract/pull/560) PR should fix the locking issue.

**Comment by mpowelson** [comment]
Addressed in #560
