### ISSUE TITLE
SRDF Parser: No version number

### ISSUE THREAD

**Issue by CaffeMrDe** [ros-industrial-consortium/tesseract#586]
You can set logging level with TRAJOPT_LOG_THRESH. Valid values: FATAL ERROR WARN INFO DEBUG TRACE. Defaulting to ERROR
Warning: SRDF Parser: No version number was provided so latest parser (version: 1.0.0) will be used.
         at line 89 in /home/fshs/tesseract_ros_ws/src/tesseract/tesseract_scene_graph/src/srdf_model.cpp

This warn is fatel?

**Comment by mpowelson** [comment]
I'm not sure I understand your question, but perhaps this is related to #378? You probably need to add a version tag to your srdf.

**Comment by CaffeMrDe** [comment]
Oh, yes. As you say.
