### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by Jmeyer1292** [ros-industrial-consortium/tesseract#6]
It is a point of open investigation as to whether or not the default bullet collision library provides a thread safe interface in the same way that MoveIt's wrapper around FCL does.

**Comment by Levi-Armstrong** [comment]
Do you know if this is resolved with the latest changes?

**Comment by Jmeyer1292** [comment]
API design now enforces that the user of a tesseract environment calls either of the following functions in the environment base class:
```c++
  /** @brief Get a copy of the environments discrete contact manager */
  virtual DiscreteContactManagerBasePtr getDiscreteContactManager() const = 0;

  /** @brief Get a copy of the environments continuous contact manager */
virtual ContinuousContactManagerBasePtr getContinuousContactManager() const = 0;
```
Each contact manager should be treated as if it is NOT thread safe, but you can make one per thread to share resources efficiently.
