### ISSUE TITLE
FreeCAD integration

### ISSUE THREAD

**Issue by johnwason** [ros-industrial-consortium/tesseract#62]
FreeCAD has a (seemingly very limited) robot workbench module that can be used to set waypoints and specify paths.

https://www.freecadweb.org/wiki/Robot_Workbench

Having a tool like this integrated with Tesseract would provide capabilities similar to commercial robot planning software.

**Comment by Levi-Armstrong** [comment]
I have been very interested in building this. I have used freecad before and developed a simple plugin before.  I have been discussing this internally whether to integrate into freecad or something custom. I personally vote for freecad myself. I think it would be good to discuss at the next developers meeting.

**Comment by jf---** [comment]
perhaps interface with `tesseract` via `roslibpy`. If the drawing classes are abstract, than it becomes easy to adapt to your CAD package of preference, FreeCAD, pythonocc, rhino come to mind

**Comment by jf---** [comment]
getting back to this issue - what's pretty amazing is that a great way to install `freecad` is via [conda](https://github.com/FreeCAD/FreeCAD_Conda). having such a conda recipe might be a nice way to build towards this goal? These days `ROS` also comes with pre-build conda packages, hence it might be a good idea IMO.

Currently, how to build the project and which platforms are supported is somewhat underdocumented and its easy to separate the conda specifics from general build mechanics

**Comment by Levi-Armstrong** [comment]
We plan to leverage Ignition Robotics software packages.
