### ISSUE TITLE
add python interface?

### ISSUE THREAD

**Issue by jacknlliu** [ros-industrial-consortium/tesseract#87]

**Comment by Levi-Armstrong** [comment]
This should be available soon.

**Comment by Levi-Armstrong** [comment]
@KevinWarburton

**Comment by jf---** [comment]
FWIW, if refactoring is to be done, `pybind11` is quite a bit more convienent than generating bindings via boost

**Comment by Levi-Armstrong** [comment]
We have been using SWIG.

**Comment by jf---** [comment]
Cool thing with `pybind11` is that it supports modern C++, where SWIG is pretty much in maintenance mode

**Comment by traversaro** [comment]
> Cool thing with `pybind11` is that it supports modern C++, where SWIG is pretty much in maintenance mode. Stoked that bindings are in the pipline

Which specific features of "modern" C++ are you referring to? SWIG has some support for features of C++11 ( http://www.swig.org/Doc4.0/CPlusPlus11.html ), C++14 ( http://www.swig.org/Doc4.0/CPlusPlus14.html ) and C++17 (http://www.swig.org/Doc4.0/CPlusPlus17.html), but perhaps there are specific features only covered by `pybind11` .

**Comment by johnwason** [comment]
The Python bindings should be ready. 

https://github.com/johnwason/tesseract_python

I still need to develop unit tests and examples.

**Comment by jf---** [comment]
That's duly impressive @johnwason... 
Given the `ROS` depencies, and [conda](https://medium.com/@wolfv/ros-on-conda-forge-dca6827ac4b6) recently being able to install `ROS`, is making such a `conda` package an interesting idea?

**Comment by johnwason** [comment]
I broke up the Python into two module, `tesseract` and `tesseract_ros`. If you don't use the `tesseract_ros` package, there aren't any ROS dependencies.

**Comment by johnwason** [comment]
I have pushed some bug fixes and tests. I could not get the industrial_ci to work though. I need to build SWIG from source, but it is being built outside of the container and is not available after the industrial_ci script starts. Any suggestions on how to fix this?

@Levi-Armstrong do you want to merge the Python wrappers into the main repo?

**Comment by Levi-Armstrong** [comment]
Will a custom build of SWIG be required going forward? If so you can add swig to tesseract_ext possible using cmakes [ExternalProject_Add](https://github.com/ros-industrial-consortium/tesseract_ext). Each of the packages currently use this feature for building external dependencies. Another option would be to create a docker with your version installed. I most likely will do this for the packages in tesseract_ext to speed up CI builds.

> do you want to merge the Python wrappers into the main repo?
Absolutely

**Comment by johnwason** [comment]
For externalproject_add, we should probably check to see if the correct version is available before downloading it, and also have a flag to disable the behavior. It may prove to be a problem for other build systems like vcpgk.

**Comment by Levi-Armstrong** [comment]
Yea my next step is to take what you have done in porting tesseract and trajopt into the main repository.

**Comment by Levi-Armstrong** [comment]
@johnwason I wanted to add swig to tesseract external. Did you already create this?

**Comment by johnwason** [comment]
No, I have not worked on tesseract_ext.

**Comment by Levi-Armstrong** [comment]
Ok thanks.
