### ISSUE TITLE
Uninitialized reads reported in Valgrind

### ISSUE THREAD

**Issue by j-petit** [ros-industrial-consortium/tesseract#88]
### Error Description
When running Valgrind on the [this unit test](https://github.com/ros-industrial-consortium/tesseract/blob/master/tesseract_ros/test/kdl_env_unit.cpp) I get the following conditional jump on not initialized values messages [valgrind_output](https://github.com/ros-planning/moveit/files/3326052/valgrind_output.txt). The [code snippet in question](https://github.com/ros-industrial-consortium/tesseract/blob/740e6607423e2afbeba04b609e118043c86b7266/tesseract_ros/src/kdl/kdl_env.cpp#L751) deals with reading in the robot links from the URDF and constructing out of them the bullet collision objects. For the first constructed object, this results in an uninitialized read at [this point](https://github.com/ros-industrial-consortium/tesseract/blob/740e6607423e2afbeba04b609e118043c86b7266/tesseract_collision/src/bullet/bullet_utils.cpp#L304). 

### System Description
Description:    Ubuntu 18.04.2 LTS
Release:    18.04
Codename:   bionic

Linux jp-XPS-15-9550 4.15.0-51-generic
x86_64 x86_64 x86_64 GNU/Linux

```
ROS_DISTRO=melodic
ROS_ETC_DIR=/opt/ros/melodic/etc/ros
ROS_PACKAGE_PATH=/opt/ros/melodic/share
ROS_PYTHON_VERSION=2
ROS_VERSION=1
ROS_ROOT=/opt/ros/melodic/share/ros
ROS_MASTER_URI=http://localhost:11311
ROSLISP_PACKAGE_DIRECTORIES=
```

**Comment by Levi-Armstrong** [comment]
This has been solved in PR #72. We are finalizing some remaining changes this week and should be able to merge next week into master branch.

**Comment by felixvd** [comment]
Is there any way you might remember what the problem was or where it was fixed? That PR is 130,000 lines long(!)

**Comment by Levi-Armstrong** [comment]
Sorry I do not, We have been rewriting everything so there has been a lot of changes.

**Comment by mpowelson** [comment]
@Levi-Armstrong Since #72 has been merged, should this be closed?

**Comment by Levi-Armstrong** [comment]
It might be good to rerun valgrind to confirm.

**Comment by Levi-Armstrong** [comment]
Closing, please reopen if needed.
